version: "2"

run:
  concurrency: 4
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - bodyclose
    - dogsled
    - dupl
    - funlen
    - goconst
    - gocyclo
    - gosec
    - lll
    - misspell
    - nakedret
    - revive
    - unconvert
    - unparam
    - whitespace

  settings:
    funlen:
      lines: 120
      statements: 60
    gocyclo:
      min-complexity: 15
    lll:
      line-length: 120
    revive:
      severity: warning

  exclusions:
    default-exclusions: false   
    rules:                     
      - linters:
          - revive
        text: "exported: exported"
      - linters:
          - revive
        text: "package-comments"
      - path: _test\.go
        linters:
          - funlen

issues:
  max-issues-per-linter: 0
  max-same-issues: 0