// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: bookings.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelBooking = `-- name: CancelBooking :one
UPDATE bookings
SET status = 'cancelled', updated_at = NOW()
WHERE id = $1 AND status = 'pending'
RETURNING id, event_id, user_email, status, created_at, updated_at
`

func (q *Queries) CancelBooking(ctx context.Context, id pgtype.UUID) (Booking, error) {
	row := q.db.QueryRow(ctx, cancelBooking, id)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.UserEmail,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const confirmBooking = `-- name: ConfirmBooking :one
UPDATE bookings
SET status = 'confirmed', updated_at = NOW()
WHERE id = $1 AND status = 'pending'
RETURNING id, event_id, user_email, status, created_at, updated_at
`

func (q *Queries) ConfirmBooking(ctx context.Context, id pgtype.UUID) (Booking, error) {
	row := q.db.QueryRow(ctx, confirmBooking, id)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.UserEmail,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createBooking = `-- name: CreateBooking :one
INSERT INTO bookings (id, event_id, user_email, status, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, event_id, user_email, status, created_at, updated_at
`

type CreateBookingParams struct {
	ID        pgtype.UUID        `json:"id"`
	EventID   pgtype.UUID        `json:"event_id"`
	UserEmail string             `json:"user_email"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateBooking(ctx context.Context, arg CreateBookingParams) (Booking, error) {
	row := q.db.QueryRow(ctx, createBooking,
		arg.ID,
		arg.EventID,
		arg.UserEmail,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.UserEmail,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBooking = `-- name: DeleteBooking :exec
DELETE FROM bookings
WHERE id = $1
`

func (q *Queries) DeleteBooking(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteBooking, id)
	return err
}

const getBookingByID = `-- name: GetBookingByID :one
SELECT id, event_id, user_email, status, created_at, updated_at FROM bookings
WHERE id = $1
`

func (q *Queries) GetBookingByID(ctx context.Context, id pgtype.UUID) (Booking, error) {
	row := q.db.QueryRow(ctx, getBookingByID, id)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.UserEmail,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBookings = `-- name: ListBookings :many
SELECT id, event_id, user_email, status, created_at, updated_at FROM bookings
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListBookingsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListBookings(ctx context.Context, arg ListBookingsParams) ([]Booking, error) {
	rows, err := q.db.Query(ctx, listBookings, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Booking
	for rows.Next() {
		var i Booking
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.UserEmail,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBooking = `-- name: UpdateBooking :one
UPDATE bookings
SET event_id = $2, user_email = $3, status = $4, updated_at = $5
WHERE id = $1
RETURNING id, event_id, user_email, status, created_at, updated_at
`

type UpdateBookingParams struct {
	ID        pgtype.UUID        `json:"id"`
	EventID   pgtype.UUID        `json:"event_id"`
	UserEmail string             `json:"user_email"`
	Status    string             `json:"status"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateBooking(ctx context.Context, arg UpdateBookingParams) (Booking, error) {
	row := q.db.QueryRow(ctx, updateBooking,
		arg.ID,
		arg.EventID,
		arg.UserEmail,
		arg.Status,
		arg.UpdatedAt,
	)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.UserEmail,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
