// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: outbox.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOutboxEvent = `-- name: CreateOutboxEvent :one
INSERT INTO outbox_events (id, event_name, event_data, destination)
VALUES ($1, $2, $3, $4)
RETURNING id, event_name, event_data, status, destination, created_at, updated_at
`

type CreateOutboxEventParams struct {
	ID          pgtype.UUID `json:"id"`
	EventName   string      `json:"event_name"`
	EventData   []byte      `json:"event_data"`
	Destination string      `json:"destination"`
}

func (q *Queries) CreateOutboxEvent(ctx context.Context, arg CreateOutboxEventParams) (OutboxEvent, error) {
	row := q.db.QueryRow(ctx, createOutboxEvent,
		arg.ID,
		arg.EventName,
		arg.EventData,
		arg.Destination,
	)
	var i OutboxEvent
	err := row.Scan(
		&i.ID,
		&i.EventName,
		&i.EventData,
		&i.Status,
		&i.Destination,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPendingOutboxEvents = `-- name: GetPendingOutboxEvents :many
SELECT id, event_name, event_data, status, destination, created_at, updated_at FROM outbox_events
WHERE status = 'pending'
ORDER BY created_at ASC
LIMIT $1
FOR UPDATE SKIP LOCKED
`

func (q *Queries) GetPendingOutboxEvents(ctx context.Context, limit int32) ([]OutboxEvent, error) {
	rows, err := q.db.Query(ctx, getPendingOutboxEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OutboxEvent
	for rows.Next() {
		var i OutboxEvent
		if err := rows.Scan(
			&i.ID,
			&i.EventName,
			&i.EventData,
			&i.Status,
			&i.Destination,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOutBoxEventAsProcessed = `-- name: MarkOutBoxEventAsProcessed :exec
UPDATE outbox_events
SET status = 'processed', updated_at = NOW()
WHERE id = $1
`

func (q *Queries) MarkOutBoxEventAsProcessed(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markOutBoxEventAsProcessed, id)
	return err
}
