// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error)
	DeleteEvent(ctx context.Context, id pgtype.UUID) error
	GetEvent(ctx context.Context, id pgtype.UUID) (Event, error)
	ListEvents(ctx context.Context, arg ListEventsParams) ([]Event, error)
	UpdateEvent(ctx context.Context, arg UpdateEventParams) (Event, error)
}

var _ Querier = (*Queries)(nil)
