// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CancelBooking(ctx context.Context, id pgtype.UUID) (Booking, error)
	ConfirmBooking(ctx context.Context, id pgtype.UUID) (Booking, error)
	CreateBooking(ctx context.Context, arg CreateBookingParams) (Booking, error)
	CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error)
	DeleteBooking(ctx context.Context, id pgtype.UUID) error
	DeleteEvent(ctx context.Context, id pgtype.UUID) error
	GetBookingByID(ctx context.Context, id pgtype.UUID) (Booking, error)
	GetEvent(ctx context.Context, id pgtype.UUID) (Event, error)
	ListBookings(ctx context.Context, arg ListBookingsParams) ([]Booking, error)
	ListEvents(ctx context.Context, arg ListEventsParams) ([]Event, error)
	ReserveSpots(ctx context.Context, arg ReserveSpotsParams) (Event, error)
	UpdateBooking(ctx context.Context, arg UpdateBookingParams) (Booking, error)
	UpdateEvent(ctx context.Context, arg UpdateEventParams) (Event, error)
}

var _ Querier = (*Queries)(nil)
